### PR TITLE
Add instructions for using Route53 for DNS

### PR DESCRIPTION
**Pull request by brokebit**
Add instructions for using Route53 for DNS

### CODE REVIEW

**Comment by mdevaev** [comment]
Can we move credential directory to some other place, just so as not to clutter up rootfs?

**Comment by brokebit** [comment]
Hi Maxin - My preference too would be not to put it in root of the filesystem. I tried to put it on other locations such as _/root/.aws/credentials_ and in the rw PST volume. But none of those options worked. 

I think the issue is how the boto library, which is used by certbot-dns-route53, works. Boto looks for the credentials file in either the user's home directory or in a path specified in the environment variable called AWS_SHARED_CREDENTIALS_FILE. 

In the first case, the kvmd daemons run as users whose homes are all the file system's root. So naturally, boto will want to look in _/.aws/credentials_ instead of _/root/.aws/credentials_ or any other path. 

In the second case, I tried to export the AWS_SHARED_CREDENTIALS_FILE variable before running _kvmd-certbot_. It seems to be ignored. I hypothesize that the _kvmd-cerbot_ command is not passing exported environment variables to the environment that ends up running the _certbot_ command. 

The CloudFlare plugin appears to have a CLI switch, --dns-cloudflare-credentials, to specify a path to the credentials files. Unfortunately, the Route53 plugin doesn't offer such a switch. 

So, in the end, _/.aws/credentials_ was the only path I could get to work. 

If you know of a way to place the file in PST and specify the credentials path, which is likely the preferred approach, I'd love to learn about it. 

Eric

**Comment by mdevaev** [comment]
Try to update to KVMD 3.118. Now you can pass environment variables into pstrun (like `FOO=bar kvmd-pstrun ...`), and you can write varilables to `/etc/conf.d/kvmd-certbot`. Please try it.

**Comment by brokebit** [comment]
Hi Maxim - Thanks for the quick fix. However, I still don't think the environment variables are making it through for boto. 

**[root@pikvm kvmd-webterm]# cat /etc/conf.d/kvmd-certbot** 
```
AWS_SHARED_CREDENTIALS_FILE="/var/lib/kvmd/pst/data/certbot/runroot/.aws.auth"
```

**[root@pikvm kvmd-webterm]# ls -al /var/lib/kvmd/pst/data/certbot/runroot/.aws.auth**
```
-rw------- 1 kvmd-certbot kvmd-certbot 112 Jul  2 22:44 /var/lib/kvmd/pst/data/certbot/runroot/.aws.auth
```

**[root@pikvm kvmd-webterm]# cat /var/lib/kvmd/pst/data/certbot/runroot/.aws.auth**
```
[default]
aws_access_key_id=XXXXXXXXXXX
aws_secret_access_key=XXXXXXXXXXX
```

**[root@pikvm kvmd-webterm]# kvmd-certbot certonly --dns-route53 --agree-tos -n --email eric@xxxxxxx.com -d kvm.xxxxxxx.io**
```
--    INFO -- Opening PST session ...
--    INFO -- PST write is allowed: /var/lib/kvmd/pst/data
--    INFO -- Running the process ...
+ mkdir -p /var/lib/kvmd/pst/data/certbot/runroot
+ chown -R kvmd-certbot: /var/lib/kvmd/pst/data/certbot/runroot/..
--    INFO -- Process finished: returncode=0
--    INFO -- Opening PST session ...
--    INFO -- PST write is allowed: /var/lib/kvmd/pst/data
--    INFO -- Running the process ...
Saving debug log to /var/lib/kvmd/pst/data/certbot/runroot/logs/letsencrypt.log
Requesting a certificate for kvm.dynowski.io
Unable to locate credentials
To use certbot-dns-route53, configure credentials as described at https://boto3.readthedocs.io/en/latest/guide/configuration.html#best-practices-for-configuring-credentials and add the necessary permissions for Route53 access.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/lib/kvmd/pst/data/certbot/runroot/logs/letsencrypt.log or re-run Certbot with -v for more details.
--    INFO -- Process finished: returncode=1
```

**[root@pikvm kvmd-webterm]#  tail -50 /var/lib/kvmd/pst/data/certbot/runroot/logs/letsencrypt.log**
```
    http, parsed_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/botocore/client.py", line 921, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/lib/python3.10/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/lib/python3.10/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/lib/python3.10/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/usr/lib/python3.10/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/lib/python3.10/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/usr/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/usr/lib/python3.10/site-packages/botocore/signers.py", line 103, in handler
    return self.sign(operation_name, request)
  File "/usr/lib/python3.10/site-packages/botocore/signers.py", line 187, in sign
    auth.add_auth(request)
  File "/usr/lib/python3.10/site-packages/botocore/auth.py", line 407, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python3.10/site-packages/certbot/_internal/main.py", line 1744, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.10/site-packages/certbot/_internal/main.py", line 1591, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python3.10/site-packages/certbot/_internal/main.py", line 141, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python3.10/site-packages/certbot/_internal/client.py", line 513, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python3.10/site-packages/certbot/_internal/client.py", line 441, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3.10/site-packages/certbot/_internal/client.py", line 493, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/usr/lib/python3.10/site-packages/certbot/_internal/auth_handler.py", line 86, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/lib/python3.10/site-packages/certbot_dns_route53/_internal/dns_route53.py", line 67, in perform
    raise errors.PluginError("\n".join([str(e), INSTRUCTIONS]))
certbot.errors.PluginError: Unable to locate credentials
To use certbot-dns-route53, configure credentials as described at https://boto3.readthedocs.io/en/latest/guide/configuration.html#best-practices-for-configuring-credentials and add the necessary permissions for Route53 access.
2022-07-02 22:47:52,741:ERROR:certbot._internal.log:Unable to locate credentials
To use certbot-dns-route53, configure credentials as described at https://boto3.readthedocs.io/en/latest/guide/configuration.html#best-practices-for-configuring-credentials and add the necessary permissions for Route53 access.
```

**Comment by mdevaev** [comment]
Try `AWS_SHARED_CREDENTIALS_FILE="/var/lib/kvmd/pst/data/certbot/runroot/.aws.auth" kvmd-certbot certonly --dns-route53 --agree-tos -n --email eric@xxxxxxx.com -d kvm.xxxxxxx.io`

**Comment by brokebit** [comment]
Same result:

**[root@pikvm kvmd-webterm]# AWS_SHARED_CREDENTIALS_FILE="/var/lib/kvmd/pst/data/certbot/runroot/.aws.auth" kvmd-certbot certonly --dns-route53 --agree-tos -n --email eric@xxxxxxxx.com -d kvm.xxxxxxxxxx.io**
```
--    INFO -- Opening PST session ...
--    INFO -- PST write is allowed: /var/lib/kvmd/pst/data
--    INFO -- Running the process ...
+ mkdir -p /var/lib/kvmd/pst/data/certbot/runroot
+ chown -R kvmd-certbot: /var/lib/kvmd/pst/data/certbot/runroot/..
--    INFO -- Process finished: returncode=0
--    INFO -- Opening PST session ...
--    INFO -- PST write is allowed: /var/lib/kvmd/pst/data
--    INFO -- Running the process ...
Saving debug log to /var/lib/kvmd/pst/data/certbot/runroot/logs/letsencrypt.log
Requesting a certificate for kvm.dynowski.io
Unable to locate credentials
To use certbot-dns-route53, configure credentials as described at https://boto3.readthedocs.io/en/latest/guide/configuration.html#best-practices-for-configuring-credentials and add the necessary permissions for Route53 access.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/lib/kvmd/pst/data/certbot/runroot/logs/letsencrypt.log or re-run Certbot with -v for more details.
--    INFO -- Process finished: returncode=1
```

**Comment by mdevaev** [comment]
What about
```
export AWS_SHARED_CREDENTIALS_FILE="/var/lib/kvmd/pst/data/certbot/runroot/.aws.auth"
kvmd-certbot certonly --dns-route53 --agree-tos -n --email [eric@xxxxxxxx.com](mailto:eric@xxxxxxxx.com) -d kvm.xxxxxxxxxx.io
```
?

**Comment by brokebit** [comment]
Tried two versions of that. The first failed due to parsing issues. The second had the same result. The exported variable is not being passed up the chain to boto. 

**[root@pikvm conf.d]# export AWS_SHARED_CREDENTIALS_FILE="/var/lib/kvmd/pst/data/certbot/runroot/.aws.auth" kvmd-certbot certonly --dns-route53 --agree-tos -n --email eric@xxxxxxxxx.com -d kvm.xxxxxxxxxxx.io**
```
bash: export: `kvmd-certbot': not a valid identifier
bash: export: `--dns-route53': not a valid identifier
bash: export: `--agree-tos': not a valid identifier
bash: export: `-n': not a valid identifier
bash: export: `--email': not a valid identifier
bash: export: `eric@xxxxxxxxxx.com': not a valid identifier
bash: export: `-d': not a valid identifier
bash: export: `kvm.xxxxxxxxx.io': not a valid identifier
```

**[root@pikvm conf.d]# export AWS_SHARED_CREDENTIALS_FILE="/var/lib/kvmd/pst/data/certbot/runroot/.aws.auth"**
**[root@pikvm conf.d]# kvmd-certbot certonly --dns-route53 --agree-tos -n --email eric@xxxxxxxxx.com -d kvm.xxxxxxxxxxx.io**
```
--    INFO -- Opening PST session ...
--    INFO -- PST write is allowed: /var/lib/kvmd/pst/data
--    INFO -- Running the process ...
+ mkdir -p /var/lib/kvmd/pst/data/certbot/runroot
+ chown -R kvmd-certbot: /var/lib/kvmd/pst/data/certbot/runroot/..
--    INFO -- Process finished: returncode=0
--    INFO -- Opening PST session ...
--    INFO -- PST write is allowed: /var/lib/kvmd/pst/data
--    INFO -- Running the process ...
Saving debug log to /var/lib/kvmd/pst/data/certbot/runroot/logs/letsencrypt.log
Requesting a certificate for kvm.xxxxxxxxxxx.io
Unable to locate credentials
To use certbot-dns-route53, configure credentials as described at https://boto3.readthedocs.io/en/latest/guide/configuration.html#best-practices-for-configuring-credentials and add the necessary permissions for Route53 access.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/lib/kvmd/pst/data/certbot/runroot/logs/letsencrypt.log or re-run Certbot with -v for more details.
--    INFO -- Process finished: returncode=1
[root@pikvm conf.d]# 
````

**Comment by brokebit** [comment]
An alternative approach might be to consider moving the home directories for the various kvmd-* users from / to a directory under /home?

**Comment by mdevaev** [comment]
Is the AWS_SHARED_CREDENTIALS_FILE really working? I throw the environment variable and if certbot really uses it, then everything should work. Maybe it's called something else? Could you try a regular certbot on your local machine (not pikvm) with non-standard location of the credentials file? We need to check if it's working at all.

> An alternative approach might be to consider moving the home directories for the various kvmd-* users from / to a directory under /home?

This is a special case that could potentially break other applications.

> Though that might introduce some permissions issues.

Indeed!

**Comment by brokebit** [comment]
Good idea. I’m pretty sure that’s the right variable. At least based on the Boto documentation. But I will put up a fresh Arch Linux VM later this evening and test.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by brokebit** [comment]
I've confirmed that the AWS_SHARED_CREDENTIALS_FILE variable works as expected on a fresh install of ArchLinux in a virtual machine. Below are two attempts. The first is without the variable set, and the second is with it set.

**[root@arch1 ~]# certbot certonly --dns-route53 --email eric@xxxxxxx.com -d kvm.xxxxxxx.io**
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requesting a certificate for kvm.xxxxxxxxx.io
Unable to locate credentials
To use certbot-dns-route53, configure credentials as described at https://boto3.readthedocs.io/en/latest/guide/configuration.html#best-practices-for-configuring-credentials and add the necessary permissions for Route53 access.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
```


**[root@arch1 ~]# export AWS_SHARED_CREDENTIALS_FILE=/root/.aws.auth 
[root@arch1 ~]# certbot certonly --dns-route53 --email eric@xxxxxxx.com -d kvm.xxxxxx.io**
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requesting a certificate for kvm.dynowski.io

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/kvm.xxxx.io/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/kvm.xxxx.io/privkey.pem
This certificate expires on 2022-10-01.
These files will be updated when the certificate renews.

NEXT STEPS:
- The certificate will need to be renewed before it expires. Certbot can automatically renew the certificate in the background, but you may need to take steps to enable that functionality. See https://certbot.org/renewal-setup for instructions.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

**Comment by brokebit** [comment]
Hi Maxim - I did a little poking around this morning at the kvmd-certbot script, and I'm pretty sure the variables are not making it to certbot because you are using sudo. 

Sudo has an option called --preserve-env. I modified the kvmd-certbot script and added --preserve-env" to every instance of the sudo command. 

I then exported the AWS_SHARED_CREDENTIALS_FILE variable, ran kvmd-certbot and was able to get a certificate.

**Comment by mdevaev** [comment]
Nice catch! Fixed in 3.119. Please update the doc and I will merge it.

**Comment by brokebit** [comment]
Thanks for your help. Documentation updated and tested. 

One new minor item, certbot is throwing some errors, but it doesn't seem to impact the outcome and everything works. Notice the **"Hook 'deploy-hook' ran with error output:"** errors below. They seem to be failing when certbot is changing permissions. But, I am still able to successfully complete the setup and use the new certs. 

From what I can tell, certbot is trying to change permissions on files in the PST partition. But instead of using pstrun it's just doing a direct chmod and probably getting a read-only filesystem errors.   

[root@pikvm /]# kvmd-certbot certonly --dns-route53 --agree-tos -n --email eric@xxxxxxx.com -d pikvm.xxxxxxx.io
```
--    INFO -- Opening PST session ...
--    INFO -- PST write is allowed: /var/lib/kvmd/pst/data
--    INFO -- Running the process ...
+ mkdir -p /var/lib/kvmd/pst/data/certbot/runroot
+ chown -R kvmd-certbot: /var/lib/kvmd/pst/data/certbot/runroot/..
--    INFO -- Process finished: returncode=0
--    INFO -- Opening PST session ...
--    INFO -- PST write is allowed: /var/lib/kvmd/pst/data
--    INFO -- Running the process ...
Saving debug log to /var/lib/kvmd/pst/data/certbot/runroot/logs/letsencrypt.log
Account registered.
Requesting a certificate for pikvm.xxxxxxx.io
Hook 'deploy-hook' ran with error output:
 + chmod 755 /var/lib/kvmd/pst/data/certbot/runroot/config/archive /var/lib/kvmd/pst/data/certbot/runroot/config/live
 + chmod 640 /var/lib/kvmd/pst/data/certbot/runroot/config/live/pikvm.xxxxx.io/privkey.pem

Successfully received certificate.
Certificate is saved at: /var/lib/kvmd/pst/data/certbot/runroot/config/live/pikvm.xxxxx.io/fullchain.pem
Key is saved at:         /var/lib/kvmd/pst/data/certbot/runroot/config/live/pikvm.xxxxxxx.io/privkey.pem
This certificate expires on 2022-10-01.
These files will be updated when the certificate renews.

NEXT STEPS:
- The certificate will need to be renewed before it expires. Certbot can automatically renew the certificate in the background, but you may need to take steps to enable that functionality. See https://certbot.org/renewal-setup for instructions.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
--    INFO -- Process finished: returncode=0
[root@pikvm /]#
```

**Comment by mdevaev** [comment]
Thanks!

**Pull request merged**
