### PR TITLE
Add documentation/images for TESMART KVM switch

### PR DESCRIPTION
**Pull request by davideshay**
Documentation for changes to kvmd for direct TESMART switch support over the network.

### CODE REVIEW

**Comment by mdevaev** [comment]
Please update to 2.68. I completely rewrote the plugin using asynchronous sockets. Other changes: now the port numbering starts from 0 (this is how all other plugins behave), some parameters (host, port) have been renamed, and max_ports has been removed. Please test it and let me know how it works.

**Comment by davideshay** [comment]
OK trying to test. Some strangeness... With your code, my prior code, and indeed the kvmctl.sh bash script I based this on, the switch stops responding after 4-5 commands.
The good news is that the Windows utility program (running in a VM) works just fine, so I'm trying to do some packet captures to see if there is a difference.

**Comment by davideshay** [comment]
OK finished testing -- not really sure what was going on but after I turned switch off long enough and back on, the bash script, my orig. code, and windows utility were all working consistently. The rewritten code had some minor issues in testing - I submitted another pull request for the issues I found. Let me know when you want me to test again.

**Comment by mdevaev** [comment]
Fixed config.

The plugin will be available in the next release.

PS: Thanks!

**Pull request merged**
