### PR TITLE
Added manufacturer link since unavailable to the US via Amazon.de

### PR DESCRIPTION
**Pull request by JayBeale**
The Amazon.de link won't ship to the US, so I've added a link to the manufacturer's page, if that's ok?

### CODE REVIEW

**Comment by mdevaev** [comment]
It is better to use amazon.com in this case

**Comment by mdevaev** [comment]
Do you want to change it?

**Comment by JayBeale** [comment]
oh sure - can do!

**Comment by mdevaev** [comment]
Thanks!

**Pull request merged**
