### PR TITLE
Add hue.md

### PR DESCRIPTION
**Pull request by semool**

### CODE REVIEW

**Comment by mdevaev** [comment]
Please add link to the example device

**Comment by semool** [comment]
What do you mean?

**Comment by mdevaev** [comment]
I mean, add a link to the device on the manufacturer's website to the documentation.

**Comment by semool** [comment]
What a link to the Hue Bridge Page? Philips Homepage? I think everyone who will use it know what it is and have one at home.
And as i write in the MD, technicaly the Plugin can Switch Power on/off on EVERY Device connectet to the Bridge, lights, plugs no matter.
But i add a link to the SmartPlugs i am using myself.

**Comment by mdevaev** [comment]
https://github.com/pikvm/pikvm/blob/hue/pages/gpio.md#philips-hue

**Pull request closed without merging**
