### PR TITLE
Docs - Let's Encrypt - Fix Formatting on ACME DNS Example

### PR DESCRIPTION
**Pull request by jmcombs**
I noticed the formatting on the published docs was really bad (my fault!). I was able to run a local instance of Material for MKDocs (via Docker) so I could fix the formatting issues.

Mainly fixed formatting under the ACME DNS section and minor formatting fixes under the other sections.

### CODE REVIEW

**Comment by mdevaev** [comment]
Hello. I don't quite understand what's wrong with the current formatting because everything looks fine on the [site](https://docs.pikvm.org/letsencrypt/). Could you take a couple of screenshots for comparison?

**Comment by jmcombs** [comment]
@mdevaev, good question! In my original, my intent was to have a separation between Assumptions and Instructions and in instructions were a numbered list, all of which did not translate well in MkDocs.

 Here is before:



Here is after:

**Comment by mdevaev** [comment]
Thank you!

**Comment by jmcombs** [comment]
@mdevaev I’m happy to help on documentation. If you ever get an issue or feature request that is documentation related, feel free to tag me. If I can take it on, I’m happy to do so. Have a great weekend!

**Pull request merged**
