### PR TITLE
Update usb_ethernet.md

### PR DESCRIPTION
**Pull request by Stitch10925**
Adds more details about the "iface" configuration and how to configure it properly.

### CODE REVIEW

**Comment by mdevaev** [comment]
You don't need to specify ip_cmd param for this, it has the same default value. Plz fix it :)

**Comment by Stitch10925** [comment]
Updated

**Comment by mdevaev** [comment]
Thanks!

**Comment by Stitch10925** [comment]
Seems to not have merged correctly on the documentation page:

image

**Pull request merged**
