### PR TITLE
Assembly instructions for v3.3 printed case

### PR DESCRIPTION
**Pull request by johntron**

### CODE REVIEW

**Comment by mdevaev** [comment]
Sup. We found out that it is most effective to put the fan so that it sucks air from outside the case and blows inside. Can you replace that photo?

**Comment by johntron** [comment]
> Sup. We found out that it is most effective to put the fan so that it sucks air from outside the case and blows inside. Can you replace that photo?

Ah, I thought that's what I was doing 🤣. I'll change it and take a new photo next time I'm in the attic.

**Comment by johntron** [comment]
@mdevaev - I've updated the photo. I also added added a tip re:tightening the standoffs for disassembly at a later date after some frustration I faced.

**Comment by mdevaev** [comment]
Thanks!

**Pull request merged**
