### PR TITLE
Added tutorial for using cloudflared

### PR DESCRIPTION
**Pull request by solareon**
This provides a remote access solution that doesn't rely on port forwarding or requiring any software to be installed on the remote pc.

### CODE REVIEW

**Comment by ConnerVT** [comment]
Thank you!  Installing cloudflared on my PiKVM is on my To Do list.  Been searching weeks for info.

Is this tutorial complete, or a work in progress?  I will follow and give you feedback.

**Comment by arch1mede** [comment]
I feel this is a well written document but I think sadly, that the timing for this is bad as pikvm will be offering something similar

**Comment by mdevaev** [comment]
I don't really see a problem with that. Let people choose what they like best. I merge it, but a little later, now I have very little time to carefully read this document.

**Comment by ConnerVT** [comment]
Feedback as promised:

Won't compile.  Looks as cloudflared supports quic-go up to go 1.19, current version of go is 1.20 (which looks to have dropped a couple weeks ago).  I'll circle back in a couple of weeks and try again.

```
root@pikvm(g:master) g:/cmd/cloudflared/]# go build
# github.com/lucas-clemente/quic-go/internal/qtls
../../vendor/github.com/lucas-clemente/quic-go/internal/qtls/go120.go:6:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
```

Disclaimer: Not a die hard dev or Linux user, but I can hold my own.  Also my first dive into using Arch.  Usually smarter than the average newbie.  But please check my work.

**Comment by ConnerVT** [comment]
Thanks for the fast reply.  I saw that on the cloudflared repo.  Working with a freshly created PiKVM image and don't have any prior go versions (and don't wish to go on a repo hunt).  Today is the last of my days off from my real job, so I'll keep an eye on cloudflared getting updated and then try again.

**Comment by mlanies** [comment]
i had no problem installing cloudflared agro

**Pull request merged**
